# Generated by Django 4.0.4 on 2022-05-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('Buyer', 'Buyer'), ('Vendor', 'Vendor')], default='Buyer', help_text='Vendors has their own shops/Buyers can buy products.', max_length=64),
        ),
    ]
