# Generated by Django 4.0.4 on 2022-05-13 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0003_userprofile_coupons_bronz_userprofile_coupons_gold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='coupons_bronz',
            new_name='coupons_bronze',
        ),
    ]
