# Generated by Django 4.0.2 on 2022-05-03 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=264, verbose_name='Blog title')),
                ('article_slug', models.SlugField(max_length=1024, unique=True)),
                ('article_content', models.TextField(verbose_name='Article Content')),
                ('article_img', models.ImageField(blank=True, upload_to='blog_images', verbose_name='Blog image')),
                ('article_published_date', models.DateTimeField(auto_now_add=True)),
                ('article_update_time', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Poster', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-article_published_date'],
            },
        ),
    ]
