# Generated by Django 4.0.2 on 2022-05-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0002_alter_article_article_img_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-quiz_date']},
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_date',
            field=models.DateField(),
        ),
    ]
