# Generated by Django 4.0.2 on 2022-05-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0003_alter_quiz_options_alter_quiz_quiz_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_date',
            field=models.DateTimeField(),
        ),
    ]
