# Generated by Django 4.0.2 on 2022-05-03 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_content', '0005_alter_quiz_quiz_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='total_marks',
            field=models.IntegerField(default=10),
        ),
        migrations.CreateModel(
            name='QuizMCQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MCQ_question', models.CharField(max_length=512)),
                ('option1', models.CharField(max_length=264)),
                ('option2', models.CharField(max_length=264)),
                ('option3', models.CharField(max_length=264)),
                ('option4', models.CharField(max_length=264)),
                ('MCQ_marks', models.IntegerField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_teacherMCQ', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
