# Generated by Django 4.0.2 on 2022-05-03 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0006_quiz_total_marks_quizmcq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='quiz_content',
        ),
        migrations.RemoveField(
            model_name='quizmcq',
            name='teacher',
        ),
        migrations.AddField(
            model_name='quiz',
            name='number_of_MCQs',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='quizmcq',
            name='quiz',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='quiz_MCQs', to='app_content.quiz'),
        ),
    ]
