# Generated by Django 4.0.2 on 2022-05-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_content', '0009_alter_quiz_number_of_mcqs_alter_quiz_total_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='number_of_MCQs',
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_content',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='QuizMCQ',
        ),
    ]
