# Generated by Django 4.0.2 on 2022-04-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0003_video_video_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_category',
            field=models.CharField(choices=[('ALL', 'All category'), ('SCIENCE', 'Science'), ('GAMING', 'Gaming'), ('MOVIES', 'Movies')], default='ALL', max_length=64),
        ),
    ]
