# Generated by Django 4.0.4 on 2022-05-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoporder',
            name='bronze',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shoporder',
            name='gold',
            field=models.IntegerField(default=0),
        ),
    ]
