# Generated by Django 4.0.2 on 2022-05-05 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'ProductCategories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='product_image')),
                ('product_name', models.CharField(max_length=264)),
                ('product_preview_text', models.TextField(max_length=300, verbose_name='Preview Text')),
                ('product_detial', models.TextField(max_length=1024, verbose_name='Product Description')),
                ('product_price', models.FloatField()),
                ('old_price', models.FloatField(default=0.0)),
                ('product_added', models.DateTimeField(auto_now_add=True)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='app_shop.productcategory')),
            ],
            options={
                'ordering': ['-product_added'],
            },
        ),
    ]
